### ISSUE TITLE
BugReport: Version 6.0.0 - ImportError: cannot import name 'display_covered' from 'coverage.results'

### ISSUE THREAD

**Issue by cdgriffith** [pytest-dev/pytest-cov#670]
# Summary

On github runner macos-latest with 6.0.0, works with 5.0.0

## Expected vs actual result

```
Processing ./dist/python_box-7.3.0-cp313-cp313-macosx_10_13_universal2.whl
Installing collected packages: python-box
Successfully installed python-box-7.3.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(pytest.console_main())
                     ~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/config/__init__.py", line 201, in console_main
    code = main()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/config/__init__.py", line 156, in main
    config = _prepareconfig(args, plugins)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
        pluginmanager=pluginmanager, args=args
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
    self.parse(args)
    ~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/config/__init__.py", line 1494, in parse
    self._preparse(args, addopts=addopts)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/config/__init__.py", line 1381, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_manager.py", line 421, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/metadata/__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/assertion/rewrite.py", line 184, in exec_module
    exec(co, module.__dict__)
    ~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pytest_cov/plugin.py", line 11, in <module>
    from coverage.results import display_covered
ImportError: cannot import name 'display_covered' from 'coverage.results' (/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/coverage/results.py)
```

# Reproducer

https://github.com/cdgriffith/Box/blob/master/.github/workflows/tests.yml#L50

## Versions

Output of relevant packages `pip list`, `python --version`, `pytest --version` etc.

pytest-cov 6.0.0 (works with 5.0.0)

Make sure you include complete output of `tox` if you use it (it will show versions of various things).

## Config

Include your `tox.ini`, `pytest.ini`, `.coveragerc`, `setup.cfg` or any relevant configuration.

Repo: https://github.com/cdgriffith/Box/tree/master

## Code

```
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install coveralls flake8 flake8-print mypy setuptools wheel twine Cython>=3.0.11
          python setup.py sdist bdist_wheel
          twine check dist/*
          pip install dist/*.whl
          rm -rf box
          python -m pytest -vv
  ```

**Comment by The-Compiler** [comment]
That function exists in coverage and was there for a while: https://github.com/nedbat/coveragepy/commit/4e5027338b93fc893c5e6e82c8a234c48f0b95e7

What version of `coverage` is installed in that environment?

**Comment by cdgriffith** [comment]
@The-Compiler coverage is version `7.6.9`

And it's weird it's only on MacOS github runner with Python 3.13.  https://github.com/cdgriffith/Box/actions/runs/12248441968
Works on older python versions and other operating systems. 

Same coverage version works with pytest-cov 5.0.0, but not 6.0.0 in that scenario

**Comment by cdgriffith** [comment]
Acutally looks like for Python 3.13 on any OS, the mac one was blocking the others, just forced a rerun on windows and it also fails https://github.com/cdgriffith/Box/actions/runs/12248441968/job/34204210340

**Comment by ionelmc** [comment]
Just small note: pytest-cov's dependencies are constrained correctly and you have this in the build logs:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytest-cov 6.0.0 requires coverage[toml]>=7.5, but you have coverage 6.5.0 which is incompatible.
```
Not sure why that doesn't stop your build process but it should (seems like a pip bug).

**Comment by cdgriffith** [comment]
Good finds, thank you! I was forcing it to latest in the requirements but didn't dig into the logs to find that! 

https://github.com/cdgriffith/Box/blob/master/requirements-test.txt#L1
