### ISSUE TITLE
Unknown pytest keyword argument after updating to 6.2.0

### ISSUE THREAD

**Issue by ondras** [pytest-dev/pytest-cov#698]
The argument used to be called `hookwrapper`. Our code broke after this rename.

```
   File "/usr/local/lib/python3.11/dist-packages/pytest_cov/plugin.py", line 318, in CovPlugin
     @pytest.hookimpl(wrapper=True)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: HookimplMarker.__call__() got an unexpected keyword argument 'wrapper'
```

**Comment by RonnyPfannschmidt** [comment]
A pluggy/pytest update is needed 

A pin for pluggy may be missing

**Comment by ionelmc** [comment]
@ondras what versions you have installed for pluggy and pytest?

This has been tested to work with pytest 8.3 and 8.4 (https://github.com/pytest-dev/pytest-cov/actions/runs/15596560198)

**Comment by RonnyPfannschmidt** [comment]
Yes

**Comment by ondras** [comment]
Thanks all, our Pluggy turned out to be just 1.0.0. The problem was solved after updating to 1.6.0.
